apiVersion: integration/v1
kind: Step
name: azure-virtual-machines-step-vm-redeploy
version: 1
summary: VM redeploy

description: |

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-virtual-machines-step-vm-redeploy
