apiVersion: integration/v1
kind: Step
name: azure-virtual-machines-step-vm-deallocate
version: 1
summary: VM deallocate

description: |

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-virtual-machines-step-vm-deallocate

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Deallocate Azure virtual machine
  content:
    apiVersion: v1
    kind: Step
    name: azure-vms-deallocate-vm
    image: relaysh/azure-virtual-machines-step-vm-deallocate
    spec:
      azure:
        connection: !Connection { type: azure, name: my-azure-account }
      waitForDeletion: true
      resourceIDs:
      - !Parameter resourceID