apiVersion: integration/v1
kind: Step
name: azure-virtual-machines-step-vm-list
version: 1
summary: List virtual machines

description: |
    This step lists the Azure virtual machines in a subscription.
build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-virtual-machines-step-vm-list

schemas:
  spec:
    source: file
    file: spec.schema.json
  output:
    source: file
    file: output.schema.json 

examples:
- summary: List Azure virtual machines
  content:
    apiVersion: v1
    kind: Step
    name: azure-vms-list-vms
    image: relaysh/azure-virtual-machines-step-vm-list
    spec:
      azure:
        connection: !Connection { type: azure, name: my-azure-account }
      resourceGroup: !Parameter resourceGroup 
