apiVersion: integration/v1
kind: Step
name: azure-virtual-machines-step-vm-list
version: 1
summary: VM list

description: |

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-virtual-machines-step-vm-list

schemas:
  spec:
    source: file
    file: spec.schema.json
  output:
    source: file
    file: output.schema.json 